var Emojis = [
    {name: 'grinning-smile-eyes', text: '😁', code: 'U+1F601'},
    {name: 'tears-of-joy', text: '😂', code: 'U+1F602'},
    {name: 'smiling-open-mouth', text: '😃', code: 'U+1F603'},
    {name: 'smiling-mouth-eyes', text: '😄', code: 'U+1F604'},
    {name: 'smiling-cold-sweat', text: '😅', code: 'U+1F605'},
    {name: 'smiling-closed-eyes', text: '😆', code: 'U+1F606'},
    {name: 'winking', text: '😉', code: 'U+1F609'},
    {name: 'smiling-eyes', text: '😊', code: 'U+1F60A'},
    {name: 'delicious-food', text: '😋', code: 'U+1F60B'},
    {name: 'relieved', text: '😌', code: 'U+1F60C'},
    {name: 'heart-shaped', text: '😍', code: 'U+1F60D'},
    {name: 'smirking', text: '😏', code: 'U+1F60F'},
    {name: 'unamused', text: '😒', code: 'U+1F612'},
    {name: 'cold-sweat', text: '😓', code: 'U+1F613'},
    {name: 'pensive', text: '😔', code: 'U+1F614'},
    {name: 'confounded', text: '😖', code: 'U+1F616'},
    {name: 'throwing-kiss', text: '😘', code: 'U+1F618'},
    {name: 'kissing-closed-eyes', text: '😚', code: 'U+1F61A'},
    {name: 'stuck-out-tongue', text: '😜', code: 'U+1F61C'},
    {name: 'tightly-closed-eyes', text: '😝', code: ''},
    {name: 'disappointed', text: '😞', code: 'U+1F61E'},
    {name: 'angry', text: '😠', code: 'U+1F620'},
    {name: 'pouting', text: '😡', code: 'U+1F621'},
    {name: 'crying', text: '😢', code: 'U+1F622'},
    {name: 'persevering', text: '😣', code: 'U+1F623'},
    {name: 'look-of-triumph', text: '😤', code: 'U+1F624'},
    {name: 'disappointed-relieved', text: '😥', code: 'U+1F625'},
    {name: 'fearful', text: '😨', code: 'U+1F628'},
    {name: 'weary', text: '😩', code: 'U+1F629'},
    {name: 'sleepy', text: '😪', code: 'U+1F62A'},
    {name: 'tired', text: '😫', code: 'U+1F62B'},
    {name: 'loudly-crying ', text: '😭', code: 'U+1F62D'},
    {name: 'mouth-cold-sweat', text: '😰', code: 'U+1F630'},
    {name: 'screaming-in-fear', text: '😱', code: 'U+1F631'},
    {name: 'astonished', text: '😲', code: 'U+1F632'},
    {name: 'flushed', text: '😳', code: 'U+1F633'},
    {name: 'dizzy', text: '😵', code: 'U+1F635'},
    {name: 'medical-mask', text: '😷', code: 'U+1F637'},
    {name: 'hands-in-celebration', text: '🙌', code: 'U+1F64C'},
    {name: 'folded-hands', text: '🙏', code: 'U+1F64F'},
    {name: 'raised-first', text: '✊', code: 'U+270A'},
    {name: 'raised-hand', text: '✋', code: 'U+270B'},
    {name: 'victory-hand', text: '✌️', code: 'U+270C'},
    {name: 'ok-hand-sign', text: '👌', code: 'U+1F44C'},
    {name: 'waving-hand-sign', text: '👋', code: 'U+1F44B'},
    {name: 'thumbs-up-sign', text: '👍', code: 'U+1F44D'},
    {name: 'clapping-hands-sign', text: '👏', code: 'U+1F44F'},
    {name: 'kiss-mark', text: '💋', code: 'U+1F48B'}
];

export default Emojis;